import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import ParticleBackground from "../components/particle/particleBackground";
import fontawesome from "../components/about/fontawesome.json";
import "font-awesome/css/font-awesome.min.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
           {/* Background animation  */}
        <ParticleBackground></ParticleBackground>

        <div className={styles.homepage}>
          <h1 className={styles.name}>Yusuke Imai</h1>
          <h3 className={styles.positionName}>Frontend Developer</h3>
        </div>

      {/* Displaying fontawesome icons  */}
        <aside className={styles.icons}>
          {fontawesome.map((font) => {
            return (
              <a href={font.href} key={font.href}>
                <i className={font.icon}></i>
              </a>
            );
          })}
        </aside>
      </main>
    </>
  );
}
